name: Publish to NPM Registry
on:
  push:
    branches: [ master ]
jobs:
  release:
    strategy:
      matrix:
        version: [18, 19]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPMJS_ACCESS_TOKEN }}