name: Publish to NPM Registry
on:
  push:
    branches: [ master ]
jobs:
  release:
    strategy:
      matrix:
        version: [18, 19]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v2.3.4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
          node-version: ${{ matrix.version }}

      - name: Buikd
        run: npm run build
      # Publish version to public repository
      - name: Publish
        run: npm publish --verbose --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}